version: "3"
services:
  mysql:
    build: ddl/.
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-password
    tty: true
    restart: always
    ports:
      - "3308:3306"
  db-backend:
    build: db-backend/.
    ports: 
      - "3145:3145"
    depends_on:
      - mysql
    restart: always
  db-frontend:
    build: db-frontend/.
    ports:
      - "8000:8000"
    depends_on:
      - db-backend
    restart: always
  db-lb:
    build: db-lb/.
    ports:
      - "80:80"
    depends_on:
      - db-frontend
    restart: always
  
